#version 450
#include "MeshStructs.hpp"

layout(std430, set = 0, binding = 0) readonly buffer RenderItemBuffer
{
    RenderItem myRenderItems[];
} inMeshBuffer;

layout(std430, set = 0, binding = 0) readonly buffer RenderObjectBuffer
{
    RenderObject myRenderObjects[];
} inObjectBuffer;

layout (local_size_x = 256) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    
    
    
    // Compute shader code
}
