#pragma once
#include "Engine/Utils/StdIncludes.hpp"
#include "Engine/Reflection/ReflectedClass.h"
#include "Engine/Reflection/ReflectionSystem.h"


#define private public
#define protected public

// BEGIN INCLUDES FOR REFLECTED TYPES
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Engine.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\EnginePch.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Animation\Skeleton.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\AssetRegistry\Asset.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\AssetRegistry\AssetContainer.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\AssetRegistry\AssetRegistry.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\JsonAsset.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\Material.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\Model.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\Shader.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\Texture.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Assets\TextureCube.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\BoxColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\CameraComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\CapsuleColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\CharacterControllerComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\ColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\ConvexColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\DirectionalLightComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\EditorCameraMovementComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\LandscapeColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\LandscapeRenderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\MeshColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\PointLightComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\RigidbodyComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\SinWaveMovementComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\SphereColliderComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\StaticMeshComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Components\TransformComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\ComponentSystem\Component.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\ComponentSystem\ComponentArray.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\ComponentSystem\ComponentSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\ComponentSystem\GameObject.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Containers\SegmentedList.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\AutoInit.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\AutoInitManager.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\Console.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\Filewatcher.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\Input.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\ThreadPool.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\Time.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Coroutines\Awaitable.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Coroutines\Coroutine.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Coroutines\CoroutineManager.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Events\EventHandler.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Events\EventObserver.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Math\Color.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Math\Heightfield.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Math\LinearColor.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Physics\PhysicsErrorCallback.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Physics\PhysicsListener.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Physics\PhysicsQueryStructs.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Physics\PhysicsSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Physics\PhysXInclude.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Reflection\ReflectedClass.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Reflection\Field.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Reflection\ReflectionSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\DebugPipeline.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\FullscreenPipeline.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\GDRPipeline.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\IndexBufferHandle.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\IndexBufferSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\Mesh.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\MeshSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\MeshUtils.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\RenderSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\SkyboxPipeline.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\TextureSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\VertexBufferHandle.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\VertexBufferSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Serialization\BinaryReader.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Serialization\BinaryWriter.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\System\System.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\System\WorldSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Systems\LandscapeSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Systems\PointLightSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\CommonMacros.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\Debug.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\OnScopeExit.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\GPUSceneSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\ResizableBuffer.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanAllocator.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanBuffer.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanContext.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanDescriptorSet.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanDevice.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanImage.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanImGui.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanPhysicalDevice.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanShaderIncluder.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanSwapChain.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Windows\WindowHandler.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\World\World.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\Aftermath\NvidiaAftermathTracker.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\Aftermath\ShaderDatabase.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\Staging\StagingBuffer.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\Staging\StagingSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\EngineProperties.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\ComponentSystem\ComponentDefines.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Containers\ContainerTypes.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Containers\List.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Containers\MutexList.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\CheckDefine.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Core\EngineDefines.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Delegate.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\MulticastDelegate.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Events\EventTypes.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Math\GlmUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Rendering\Vertex.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Shaders\MeshStructs.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\System\SystemManager.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\BinaryUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\HashUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\MathUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\StdIncludes.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\String.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Utils\ThreadUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanDynamicBuffer.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Vulkan\VulkanUtils.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Internal\ConstMemberFuncCtor.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Internal\FreeFuncCtor.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Internal\FuncCtor.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Internal\LambdaFuncCtor.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Engine\Delegates\Internal\MemberFuncCtor.hpp"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Editor.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\EditorPch.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Windows\EditorWindow.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Windows\HierarchyWindow.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Windows\InspectorWindow.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Windows\SelectionSystem.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Editor\Windows\Viewport.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\Game.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\GamePch.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\GameTags.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\Components\SpringArmComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\Components\Player\PlayerCameraControllerComponent.h"
#include "C:\Users\William\Documents\GitHub\VulkanEngine\Engine\Game\Components\Player\PlayerComponent.h"
// END INCLUDES FOR REFLECTED TYPES

class GeneratedReflectionData
{
public:
	static void RegisterReflectionData(Engine& inEngine)
	{
		ReflectionSystem& reflectionSystem = inEngine.GetReflectionSystem(); 


		// Create all classes.
		{
		}


		// Add all fields & add base classes.
		{
		}
	}
};
#undef private
#undef protected
